/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const workfactory = () => {
  const { nodes, materials } = useGLTF('public/models/Factory.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Node.geometry} material={materials.Cube} />
    </group>
  )
}




useGLTF.preload('../models/Factory.glb')
export default workfactory;